### PR TITLE
add method to get mac address so we can resolve IP locally

### PR DESCRIPTION
**Pull request by omriasta**
This is the first part so we can use the mac address of each unit and then resolve it locally. The rest of the changes will be in hass-kumo (check arp table for entry and setup the devices their using the new address). I kept the change here to a minimum.
Let me know if any issues.

### CODE REVIEW

**Comment by dlarrick** [comment]
I will not have a chance to look at this until the weekend (possibly Friday)

**Comment by omriasta** [comment]
No rush, just trying to help out as much as I can, like I said, this is for others, doesn't affect me since I'm on a static.

**Comment by dlarrick** [comment]
No harm in exposing MAC address regardless of whether it's useful in HA. Merging.

**Comment by omriasta** [comment]
Perfect, thanks, are you going to push a new pypi release to incorporate this? I will need to update the version in the manifest.

**Comment by dlarrick** [comment]
Done, 0.1.9

**Pull request merged**
